# Generated by Django 4.2.20 on 2025-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorite", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={"verbose_name": "Избранное", "verbose_name_plural": "Избранное"},
        ),
        migrations.AlterModelOptions(
            name="favoriterecipe",
            options={
                "default_related_name": "favorites",
                "verbose_name": "Рецепт в избранном",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.RemoveConstraint(
            model_name="favoriterecipe",
            name="unique_favorite_recipe",
        ),
        migrations.AddConstraint(
            model_name="favoriterecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "favorite"),
                name="unique_favorite_recipe",
                violation_error_message="Этот рецепт уже в избранном.",
            ),
        ),
    ]
