# Generated by Django 3.2.16 on 2025-04-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.CharField(choices=[(1, 'В корзине'), (0, 'Не в корзине')], default=0, max_length=2, verbose_name='В корзине'),
        ),
    ]
