# Generated by Django 4.2.20 on 2025-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_link",
            field=models.SlugField(
                blank=True, max_length=32, null=True, verbose_name="Короткая ссылка"
            ),
        ),
    ]
