# Generated by Django 4.2.20 on 2025-04-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_short_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "default_related_name": "recipes",
                "ordering": ("id",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=128,
                unique=True,
                verbose_name="Название ингредиента",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                default=1,
                upload_to="recipes/images/",
                verbose_name="Изображение рецепта",
            ),
            preserve_default=False,
        ),
    ]
