# Generated by Django 4.2.20 on 2025-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_shortlink_alter_ingredient_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortlink",
            name="short_link",
            field=models.CharField(
                default="iH78",
                max_length=3,
                unique=True,
                verbose_name="Короткая ссылка",
            ),
        ),
    ]
