# Generated by Django 4.2.20 on 2025-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_ingredient_options_alter_recipe_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="link",
            field=models.CharField(
                blank=True,
                max_length=5,
                unique=True,
                verbose_name="Короткая ссылка для рецепта",
            ),
        ),
    ]
