# Generated by Django 4.2.20 on 2025-04-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_alter_shortlink_short_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "default_related_name": "recipes",
                "ordering": ("created_at",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterField(
            model_name="shortlink",
            name="short_link",
            field=models.CharField(
                default="6VE5",
                max_length=3,
                unique=True,
                verbose_name="Короткая ссылка",
            ),
        ),
    ]
