# Generated by Django 4.2.20 on 2025-04-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_subscribed",
        ),
    ]
