# Generated by Django 4.2.20 on 2025-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_is_subscribed"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="prevent_self_subscription",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(("subscriber", models.F("subscribing")), _negated=True),
                name="prevent_self_subscription",
                violation_error_message="Нельзя подписаться на себя.",
            ),
        ),
    ]
